# Generated by Django 5.2.16 on 2026-07-21 13:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

def migrate_legacy_curriculum(apps, schema_editor):
    Concept = apps.get_model("courses", "Concept")
    Quiz = apps.get_model("courses", "Quiz")
    Question = apps.get_model("courses", "QuizQuestion")
    Option = apps.get_model("courses", "QuizAnswerOption")
    for concept in Concept.objects.all():
        lesson = concept.lessons.select_related("module__course").first()
        if lesson:
            concept.course_id = lesson.module.course_id
            concept.save(update_fields=("course",))
    lesson_ids = Question.objects.values_list("lesson_id", flat=True).distinct()
    for lesson_id in lesson_ids:
        first = Question.objects.filter(lesson_id=lesson_id).select_related("lesson__module__course").first()
        quiz = Quiz.objects.create(lesson_id=lesson_id, title=f"{first.lesson.title} quiz", is_published=first.lesson.module.course.is_published)
        for position, question in enumerate(Question.objects.filter(lesson_id=lesson_id).order_by("id"), start=1):
            question.quiz_id = quiz.id; question.position = position; question.save(update_fields=("quiz", "position"))
            if question.kind == "multiple_choice" and isinstance(question.options, list):
                for option_position, text in enumerate(question.options, start=1):
                    Option.objects.create(question_id=question.id, text=str(text), position=option_position, is_correct=(question.correct_answer == option_position - 1))


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_concept_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('position', models.PositiveIntegerField()),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ('position', 'id')},
        ),
        migrations.AddField(
            model_name='concept',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='courses.course'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('pass_mark', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('maximum_attempts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('time_limit_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('quiz__isnull', False)), fields=('quiz', 'position'), name='unique_quiz_question_position'),
        ),
        migrations.AddField(
            model_name='quizansweroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='courses.quizquestion'),
        ),
        migrations.RunPython(migrate_legacy_curriculum, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='quizansweroption',
            constraint=models.UniqueConstraint(fields=('question', 'position'), name='unique_question_option_position'),
        ),
    ]
