# Generated by Django 5.2.16 on 2026-07-21 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_quizansweroption_alter_quizquestion_options_and_more'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted')], default='started', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('maximum_score', models.PositiveIntegerField(default=0)),
                ('percentage_score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='courses.quiz')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='QuizSubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_answers', to='courses.quizquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.quizsubmission')),
            ],
        ),
        migrations.AddConstraint(
            model_name='quizsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('learner', 'quiz', 'idempotency_key'), name='unique_quiz_submission_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='quizsubmissionanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_submission_question'),
        ),
    ]
