# Generated by Django 5.2.16 on 2026-07-21 10:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citations', to='study_tools.documentchunk')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_citations', to='study_tools.message')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('message', 'chunk'), name='unique_message_chunk_citation')],
            },
        ),
    ]
