# Generated by Django 5.2.16 on 2026-07-21 10:58

import django.db.models.deletion
import hashlib
from django.conf import settings
from django.db import migrations, models

def preserve_existing_documents(apps, schema_editor):
    Document = apps.get_model("study_tools", "Document")
    Chunk = apps.get_model("study_tools", "DocumentChunk")
    Document.objects.filter(status="pending").update(status="uploaded")
    Document.objects.filter(status="error").update(status="failed")
    Document.objects.filter(course__isnull=False).update(visibility="course")
    for document in Document.objects.all().iterator():
        chunks = list(Chunk.objects.filter(document=document).order_by("position"))
        for chunk in chunks:
            chunk.character_count = len(chunk.text)
            chunk.token_count = len(chunk.text.split())
            chunk.end_position = len(chunk.text)
            chunk.content_checksum = hashlib.sha256(f"legacy:{chunk.position}:{chunk.text}".encode()).hexdigest()
            chunk.save(update_fields=("character_count", "token_count", "end_position", "content_checksum"))
        document.chunk_count = len(chunks)
        document.save(update_fields=("chunk_count",))


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_concept_created_by'),
        ('study_tools', '0002_citation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=128)),
                ('operation', models.CharField(choices=[('embedding', 'Embedding'), ('generation', 'Generation')], max_length=16)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('input_characters', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='documentchunk',
            name='unique_chunk_position',
        ),
        migrations.AddField(
            model_name='conversation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='document',
            name='checksum',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='chunk_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='embedding_dimensions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='document',
            name='embedding_provider',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('course', 'Course')], db_index=True, default='private', max_length=16),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='character_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='content_checksum',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_dimensions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='end_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='processing_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='section_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='start_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='token_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=16),
        ),
        migrations.RunPython(preserve_existing_documents, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('checksum', ''), _negated=True)), fields=('owner', 'checksum'), name='unique_active_owner_document_checksum'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(fields=('document', 'processing_version', 'position'), name='unique_chunk_version_position'),
        ),
        migrations.AddConstraint(
            model_name='documentchunk',
            constraint=models.UniqueConstraint(condition=models.Q(('content_checksum', ''), _negated=True), fields=('document', 'processing_version', 'content_checksum'), name='unique_chunk_version_checksum'),
        ),
        migrations.AddField(
            model_name='providerusage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_usage', to=settings.AUTH_USER_MODEL),
        ),
    ]
