# Generated by Django 5.2.16 on 2026-07-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_tools', '0003_providerusage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at', 'id')},
        ),
    ]
