# Generated by Django 5.2.16 on 2026-07-21 13:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_quizansweroption_alter_quizquestion_options_and_more'),
        ('study_tools', '0004_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='courses.concept'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='courses.course'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='calendar_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_blocks', to='courses.course'),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='recurrence',
            field=models.CharField(choices=[('once', 'One time'), ('weekly', 'Weekly')], default='weekly', max_length=16),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='recurrence_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='recurrence_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='weekday',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.CreateModel(
            name='FlashcardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('previous_interval_days', models.PositiveIntegerField(default=0)),
                ('next_interval_days', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, max_length=64)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='study_tools.flashcard')),
            ],
            options={
                'ordering': ('-reviewed_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('card', 'idempotency_key'), name='unique_card_review_idempotency')],
            },
        ),
    ]
