# Generated by Django 5.2.16 on 2026-07-21 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_archived_at_course_archived_by_and_more'),
        ('study_tools', '0005_flashcard_concept_flashcard_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='quarantine_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='scan_provider',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='scan_result',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'Awaiting scan'), ('scanning', 'Scanning'), ('clean', 'Clean'), ('suspicious', 'Suspicious'), ('infected', 'Infected'), ('unavailable', 'Scanner unavailable')], db_index=True, default='clean', max_length=16),
        ),
        migrations.AddField(
            model_name='document',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['course', 'status', 'deleted_at'], name='study_tools_course__842655_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'status'], name='study_tools_owner_i_b4e2dc_idx'),
        ),
    ]
