# Generated by Django 5.2.16 on 2026-07-21 15:27

import study_tools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_tools', '0007_pgvector_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to=study_tools.models.private_document_key),
        ),
    ]
